# vim: ft=tmux
# Grayscale — matches Starship prompt

set-option -g display-panes-active-colour colour252
set-option -g display-panes-colour colour245

set-window-option -g clock-mode-colour colour252
