preload = /home/vchun/Pictures/Wallpapers/a_black_computer_monitor_with_a_white_screen.jpg

wallpaper = eDP-1,/home/vchun/Pictures/Wallpapers/a_black_computer_monitor_with_a_white_screen.jpg
wallpaper = DP-1,/home/vchun/Pictures/Wallpapers/a_black_computer_monitor_with_a_white_screen.jpg
wallpaper = DP-2,/home/vchun/Pictures/Wallpapers/a_black_computer_monitor_with_a_white_screen.jpg
